[package]
name = "axsyscall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-syscalls = "0.3.2"

# axhal = { path = "../axhal" }
axlog = { path = "../axlog" }